### ISSUE TITLE
vite build fails

### ISSUE THREAD

**Issue by verschoof** [desandro/masonry#1201]
```
error during build:
Could not resolve "./item" from "./item?commonjs-external"
file: ./item?commonjs-external
    at getRollupError (file:///opt/project/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file:///opt/project/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
    at ModuleLoader.handleInvalidResolvedId (file:///opt/project/node_modules/rollup/dist/es/shared/node-entry.js:19273:24)
    at file:///opt/project/node_modules/rollup/dist/es/shared/node-entry.js:19233:26
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [node] Error 1
```

**Comment by karlvr** [comment]
I have resolved this by patching the module locally using `pnpm patch`... you can achieve the same thing with [`patch-package`](https://www.npmjs.com/package/patch-package).

This problem is the `require('./item')` in `dist/masonry.pkgd.js`.

```patch
diff --git a/dist/masonry.pkgd.js b/dist/masonry.pkgd.js
index 4274bfc194d4012703cb47e33cf81c96244ff092..39df9232e57ccffbe64731629792740acba41cb4 100644
--- a/dist/masonry.pkgd.js
+++ b/dist/masonry.pkgd.js
@@ -1338,7 +1338,7 @@ return Item;
         'ev-emitter/ev-emitter',
         'get-size/get-size',
         'fizzy-ui-utils/utils',
-        './item'
+        // './item'
       ],
       function( EvEmitter, getSize, utils, Item ) {
         return factory( window, EvEmitter, getSize, utils, Item);
@@ -1351,7 +1351,7 @@ return Item;
       require('ev-emitter'),
       require('get-size'),
       require('fizzy-ui-utils'),
-      require('./item')
+      // require('./item')
     );
   } else {
     // browser global
```
